services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=etastocks'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
  cache:
    image: 'redis:latest'
    restart: 'always'
    ports:
      - '6379:6379'